"""resume_rewrites: rewritten resume saved per (resume upload, job).

简历改写结果按（上传的简历, 岗位）保存：用户确认删除建议、回填占位后的完整简历存这里，不覆盖画像，
所以排序/匹配仍用通用简历。按 resume_upload_id 区分是因为画像可以换成另一份简历，换了之后不应读到旧简历的改写稿。
source_hash 是保存时画像简历的哈希：同一条上传记录被 PUT /profile 原地改过后，据此标记改写稿已过时（不删除，里面有用户回填的真实数据）。

Revision ID: 20261002_0013
Revises: 20261002_0012
Create Date: 2026-10-02
"""

from typing import Sequence, Union

from alembic import op


revision: str = "20261002_0013"
down_revision: Union[str, None] = "20261002_0012"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute(
        """
        CREATE TABLE resume_rewrites (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            resume_upload_id INTEGER NOT NULL REFERENCES resume_uploads(id) ON DELETE CASCADE,
            job_id BIGINT NOT NULL REFERENCES job_postings(id) ON DELETE CASCADE,
            resume JSONB NOT NULL,
            source_hash TEXT NOT NULL,
            updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            UNIQUE (resume_upload_id, job_id)
        );
        """
    )


def downgrade() -> None:
    op.execute("DROP TABLE resume_rewrites;")
