"""Create the normalized PostgreSQL and pgvector schema.

Revision ID: 20260929_0001
Revises: None
Create Date: 2026-09-29
"""

from typing import Sequence, Union

from alembic import op


revision: str = "20260929_0001"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.execute(
        """
        CREATE TABLE companies (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            name TEXT NOT NULL,
            normalized_name TEXT NOT NULL UNIQUE,
            website_url TEXT,
            created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
        );

        CREATE TABLE industries (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            name TEXT NOT NULL UNIQUE
        );

        CREATE TABLE company_industries (
            company_id BIGINT NOT NULL REFERENCES companies(id) ON DELETE RESTRICT,
            industry_id BIGINT NOT NULL REFERENCES industries(id) ON DELETE RESTRICT,
            PRIMARY KEY (company_id, industry_id)
        );
        CREATE INDEX ix_company_industries_industry ON company_industries(industry_id, company_id);

        CREATE TABLE job_sources (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            company_id BIGINT NOT NULL REFERENCES companies(id) ON DELETE RESTRICT,
            name TEXT NOT NULL UNIQUE,
            provider TEXT NOT NULL,
            identifier TEXT NOT NULL,
            enabled BOOLEAN NOT NULL DEFAULT TRUE,
            priority INTEGER NOT NULL DEFAULT 100,
            last_checked_at TIMESTAMPTZ,
            last_status TEXT,
            last_message TEXT,
            created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            UNIQUE (provider, identifier)
        );
        CREATE INDEX ix_job_sources_company ON job_sources(company_id);
        CREATE INDEX ix_job_sources_enabled_priority ON job_sources(enabled, priority, company_id);

        CREATE TABLE ingestion_runs (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            source_id BIGINT NOT NULL REFERENCES job_sources(id) ON DELETE RESTRICT,
            status TEXT NOT NULL CHECK (status IN ('running', 'succeeded', 'failed', 'partial')),
            fetched_count INTEGER NOT NULL DEFAULT 0 CHECK (fetched_count >= 0),
            changed_count INTEGER NOT NULL DEFAULT 0 CHECK (changed_count >= 0),
            expired_count INTEGER NOT NULL DEFAULT 0 CHECK (expired_count >= 0),
            error_message TEXT,
            started_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            finished_at TIMESTAMPTZ
        );
        CREATE INDEX ix_ingestion_runs_source_started ON ingestion_runs(source_id, started_at DESC);

        CREATE TABLE roles (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            canonical_name TEXT NOT NULL UNIQUE,
            category TEXT,
            description TEXT NOT NULL DEFAULT '',
            embedding VECTOR(384),
            created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
        );
        CREATE INDEX ix_roles_embedding_hnsw ON roles
        USING hnsw (embedding vector_cosine_ops) WHERE embedding IS NOT NULL;

        CREATE TABLE role_aliases (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            role_id BIGINT NOT NULL REFERENCES roles(id) ON DELETE CASCADE,
            alias TEXT NOT NULL,
            normalized_alias TEXT NOT NULL UNIQUE
        );
        CREATE INDEX ix_role_aliases_role ON role_aliases(role_id);

        CREATE TABLE skills (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            canonical_name TEXT NOT NULL,
            normalized_name TEXT NOT NULL UNIQUE,
            category TEXT,
            created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
        );

        CREATE TABLE skill_aliases (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            skill_id BIGINT NOT NULL REFERENCES skills(id) ON DELETE CASCADE,
            alias TEXT NOT NULL,
            normalized_alias TEXT NOT NULL UNIQUE
        );
        CREATE INDEX ix_skill_aliases_skill ON skill_aliases(skill_id);

        CREATE TABLE skill_relations (
            source_skill_id BIGINT NOT NULL REFERENCES skills(id) ON DELETE RESTRICT,
            target_skill_id BIGINT NOT NULL REFERENCES skills(id) ON DELETE RESTRICT,
            relation_type TEXT NOT NULL CHECK (
                relation_type IN ('parent_of', 'child_of', 'related_to', 'requires', 'transferable_to')
            ),
            weight NUMERIC(5,4) NOT NULL CHECK (weight >= 0 AND weight <= 1),
            source TEXT,
            PRIMARY KEY (source_skill_id, target_skill_id, relation_type),
            CHECK (source_skill_id <> target_skill_id)
        );
        CREATE INDEX ix_skill_relations_target ON skill_relations(target_skill_id, relation_type);

        CREATE TABLE job_postings (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            company_id BIGINT NOT NULL REFERENCES companies(id) ON DELETE RESTRICT,
            source_id BIGINT NOT NULL REFERENCES job_sources(id) ON DELETE RESTRICT,
            external_id TEXT NOT NULL,
            title TEXT NOT NULL,
            location_text TEXT,
            source_employment_type TEXT,
            source_url TEXT NOT NULL,
            status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'inactive', 'expired')),
            inactive_reason TEXT,
            first_seen_at TIMESTAMPTZ NOT NULL,
            last_seen_at TIMESTAMPTZ NOT NULL,
            created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            UNIQUE (source_id, external_id)
        );
        CREATE INDEX ix_job_postings_company_status ON job_postings(company_id, status);
        CREATE INDEX ix_job_postings_source ON job_postings(source_id);
        CREATE INDEX ix_job_postings_active ON job_postings(last_seen_at DESC) WHERE status = 'active';

        CREATE TABLE job_versions (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            job_id BIGINT NOT NULL REFERENCES job_postings(id) ON DELETE CASCADE,
            content_hash TEXT NOT NULL,
            description TEXT NOT NULL,
            raw_payload JSONB NOT NULL DEFAULT '{}'::jsonb,
            collected_at TIMESTAMPTZ NOT NULL,
            created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            UNIQUE (job_id, content_hash)
        );
        CREATE INDEX ix_job_versions_job_collected ON job_versions(job_id, collected_at DESC);
        CREATE INDEX ix_job_versions_description_fts ON job_versions USING GIN (to_tsvector('english', description));

        CREATE TABLE job_analyses (
            job_version_id BIGINT PRIMARY KEY REFERENCES job_versions(id) ON DELETE CASCADE,
            summary TEXT NOT NULL DEFAULT '',
            employment_type TEXT NOT NULL DEFAULT 'not_stated',
            candidate_type TEXT NOT NULL DEFAULT 'not_stated',
            remote_policy TEXT NOT NULL DEFAULT 'not_stated',
            degree_required TEXT NOT NULL DEFAULT 'not_stated',
            raw_analysis JSONB NOT NULL DEFAULT '{}'::jsonb,
            created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
        );

        CREATE TABLE job_responsibilities (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            job_version_id BIGINT NOT NULL REFERENCES job_analyses(job_version_id) ON DELETE CASCADE,
            sequence_no INTEGER NOT NULL CHECK (sequence_no >= 0),
            responsibility_text TEXT NOT NULL,
            embedding VECTOR(384),
            embedding_model TEXT,
            UNIQUE (job_version_id, sequence_no)
        );
        CREATE INDEX ix_job_responsibilities_job ON job_responsibilities(job_version_id);
        CREATE INDEX ix_job_responsibilities_embedding_hnsw ON job_responsibilities
        USING hnsw (embedding vector_cosine_ops) WHERE embedding IS NOT NULL;

        CREATE TABLE job_major_requirements (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            job_version_id BIGINT NOT NULL REFERENCES job_analyses(job_version_id) ON DELETE CASCADE,
            sequence_no INTEGER NOT NULL CHECK (sequence_no >= 0),
            major_text TEXT NOT NULL,
            UNIQUE (job_version_id, sequence_no)
        );

        CREATE TABLE job_keywords (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            job_version_id BIGINT NOT NULL REFERENCES job_analyses(job_version_id) ON DELETE CASCADE,
            sequence_no INTEGER NOT NULL CHECK (sequence_no >= 0),
            keyword_text TEXT NOT NULL,
            UNIQUE (job_version_id, sequence_no)
        );

        CREATE TABLE job_source_evidence (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            job_version_id BIGINT NOT NULL REFERENCES job_analyses(job_version_id) ON DELETE CASCADE,
            sequence_no INTEGER NOT NULL CHECK (sequence_no >= 0),
            evidence_text TEXT NOT NULL,
            UNIQUE (job_version_id, sequence_no)
        );

        CREATE TABLE job_skill_requirements (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            job_version_id BIGINT NOT NULL REFERENCES job_analyses(job_version_id) ON DELETE CASCADE,
            skill_id BIGINT NOT NULL REFERENCES skills(id) ON DELETE RESTRICT,
            requirement_type TEXT NOT NULL CHECK (requirement_type IN ('required', 'preferred')),
            sequence_no INTEGER NOT NULL CHECK (sequence_no >= 0),
            source_text TEXT NOT NULL,
            UNIQUE (job_version_id, requirement_type, sequence_no)
        );
        CREATE INDEX ix_job_skill_requirements_skill ON job_skill_requirements(skill_id, requirement_type);
        CREATE INDEX ix_job_skill_requirements_job ON job_skill_requirements(job_version_id);

        CREATE TABLE job_roles (
            job_id BIGINT NOT NULL REFERENCES job_postings(id) ON DELETE CASCADE,
            role_id BIGINT NOT NULL REFERENCES roles(id) ON DELETE RESTRICT,
            confidence NUMERIC(5,4) NOT NULL DEFAULT 1 CHECK (confidence >= 0 AND confidence <= 1),
            PRIMARY KEY (job_id, role_id)
        );
        CREATE INDEX ix_job_roles_role ON job_roles(role_id, job_id);

        CREATE TABLE interview_questions (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            question_text TEXT NOT NULL,
            standard_answer TEXT NOT NULL DEFAULT '',
            question_text_en TEXT,
            standard_answer_en TEXT,
            difficulty_level TEXT NOT NULL DEFAULT 'not_stated' CHECK (
                difficulty_level IN ('easy', 'medium', 'hard', 'not_stated')
            ),
            company_id BIGINT REFERENCES companies(id) ON DELETE SET NULL,
            company_text TEXT,
            normalized_hash TEXT NOT NULL,
            collected_at TIMESTAMPTZ NOT NULL,
            created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
        );
        CREATE INDEX ix_interview_questions_hash ON interview_questions(normalized_hash);
        CREATE INDEX ix_interview_questions_company ON interview_questions(company_id);
        CREATE INDEX ix_interview_questions_fts ON interview_questions USING GIN (
            to_tsvector('english', question_text || ' ' || COALESCE(question_text_en, ''))
        );

        CREATE TABLE question_sources (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            question_id BIGINT NOT NULL REFERENCES interview_questions(id) ON DELETE CASCADE,
            source TEXT NOT NULL,
            external_id TEXT NOT NULL,
            source_url TEXT,
            raw_payload JSONB NOT NULL DEFAULT '{}'::jsonb,
            UNIQUE (source, external_id)
        );
        CREATE INDEX ix_question_sources_question ON question_sources(question_id);

        CREATE TABLE question_roles (
            question_id BIGINT NOT NULL REFERENCES interview_questions(id) ON DELETE CASCADE,
            role_id BIGINT NOT NULL REFERENCES roles(id) ON DELETE RESTRICT,
            sequence_no INTEGER NOT NULL CHECK (sequence_no >= 0),
            relevance NUMERIC(5,4) NOT NULL DEFAULT 1 CHECK (relevance >= 0 AND relevance <= 1),
            PRIMARY KEY (question_id, role_id)
        );
        CREATE INDEX ix_question_roles_role ON question_roles(role_id, question_id);

        CREATE TABLE question_skills (
            question_id BIGINT NOT NULL REFERENCES interview_questions(id) ON DELETE CASCADE,
            skill_id BIGINT NOT NULL REFERENCES skills(id) ON DELETE RESTRICT,
            sequence_no INTEGER NOT NULL CHECK (sequence_no >= 0),
            source_text TEXT NOT NULL,
            relevance NUMERIC(5,4) NOT NULL DEFAULT 1 CHECK (relevance >= 0 AND relevance <= 1),
            PRIMARY KEY (question_id, skill_id)
        );
        CREATE INDEX ix_question_skills_skill ON question_skills(skill_id, question_id);

        CREATE TABLE question_keywords (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            question_id BIGINT NOT NULL REFERENCES interview_questions(id) ON DELETE CASCADE,
            sequence_no INTEGER NOT NULL CHECK (sequence_no >= 0),
            keyword_text TEXT NOT NULL,
            UNIQUE (question_id, sequence_no)
        );

        CREATE TABLE question_embeddings (
            question_id BIGINT PRIMARY KEY REFERENCES interview_questions(id) ON DELETE CASCADE,
            embedding VECTOR(384),
            raw_embedding JSONB,
            model_name TEXT,
            model_version TEXT,
            created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
        );
        CREATE INDEX ix_question_embeddings_hnsw ON question_embeddings
        USING hnsw (embedding vector_cosine_ops) WHERE embedding IS NOT NULL;

        CREATE TABLE users (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            email TEXT UNIQUE,
            created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
        );

        CREATE TABLE user_profiles (
            user_id BIGINT PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
            profile_payload JSONB NOT NULL,
            notes TEXT NOT NULL DEFAULT '',
            work_authorization TEXT,
            graduation_date DATE,
            updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
        );

        CREATE TABLE user_target_roles (
            user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
            role_id BIGINT NOT NULL REFERENCES roles(id) ON DELETE RESTRICT,
            priority INTEGER NOT NULL CHECK (priority > 0),
            PRIMARY KEY (user_id, role_id),
            UNIQUE (user_id, priority)
        );

        CREATE TABLE user_target_industries (
            user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
            industry_id BIGINT NOT NULL REFERENCES industries(id) ON DELETE RESTRICT,
            PRIMARY KEY (user_id, industry_id)
        );

        CREATE TABLE resumes (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
            legacy_resume_upload_id BIGINT UNIQUE,
            filename TEXT,
            storage_uri TEXT,
            file_hash TEXT,
            parsed_payload JSONB NOT NULL,
            uploaded_at TIMESTAMPTZ NOT NULL,
            created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
        );
        CREATE INDEX ix_resumes_user_uploaded ON resumes(user_id, uploaded_at DESC);

        CREATE TABLE resume_evidence (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            resume_id BIGINT NOT NULL REFERENCES resumes(id) ON DELETE CASCADE,
            evidence_type TEXT NOT NULL CHECK (evidence_type IN ('experience', 'project', 'research')),
            sequence_no INTEGER NOT NULL CHECK (sequence_no >= 0),
            title TEXT NOT NULL,
            organization TEXT,
            summary TEXT NOT NULL DEFAULT '',
            raw_payload JSONB NOT NULL DEFAULT '{}'::jsonb,
            embedding VECTOR(384),
            embedding_model TEXT,
            UNIQUE (resume_id, evidence_type, sequence_no)
        );
        CREATE INDEX ix_resume_evidence_resume ON resume_evidence(resume_id, evidence_type);
        CREATE INDEX ix_resume_evidence_embedding_hnsw ON resume_evidence
        USING hnsw (embedding vector_cosine_ops) WHERE embedding IS NOT NULL;

        CREATE TABLE resume_skills (
            resume_id BIGINT NOT NULL REFERENCES resumes(id) ON DELETE CASCADE,
            skill_id BIGINT NOT NULL REFERENCES skills(id) ON DELETE RESTRICT,
            sequence_no INTEGER NOT NULL CHECK (sequence_no >= 0),
            source_text TEXT NOT NULL,
            PRIMARY KEY (resume_id, skill_id)
        );
        CREATE INDEX ix_resume_skills_skill ON resume_skills(skill_id, resume_id);

        CREATE TABLE match_runs (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
            resume_id BIGINT NOT NULL REFERENCES resumes(id) ON DELETE RESTRICT,
            algorithm_version TEXT NOT NULL,
            weights JSONB NOT NULL,
            created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
        );
        CREATE INDEX ix_match_runs_user_created ON match_runs(user_id, created_at DESC);

        CREATE TABLE job_match_results (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            match_run_id BIGINT NOT NULL REFERENCES match_runs(id) ON DELETE CASCADE,
            job_id BIGINT NOT NULL REFERENCES job_postings(id) ON DELETE RESTRICT,
            required_skill_score NUMERIC(6,3) NOT NULL CHECK (required_skill_score BETWEEN 0 AND 100),
            responsibility_score NUMERIC(6,3) NOT NULL CHECK (responsibility_score BETWEEN 0 AND 100),
            graph_skill_score NUMERIC(6,3) NOT NULL CHECK (graph_skill_score BETWEEN 0 AND 100),
            career_intent_score NUMERIC(6,3) NOT NULL CHECK (career_intent_score BETWEEN 0 AND 100),
            preferred_skill_bonus NUMERIC(5,3) NOT NULL CHECK (preferred_skill_bonus BETWEEN 0 AND 5),
            final_score NUMERIC(6,3) NOT NULL CHECK (final_score BETWEEN 0 AND 100),
            explanation JSONB NOT NULL DEFAULT '{}'::jsonb,
            UNIQUE (match_run_id, job_id)
        );
        CREATE INDEX ix_job_match_results_rank ON job_match_results(match_run_id, final_score DESC);

        CREATE TABLE migration_legacy_rows (
            source_table TEXT NOT NULL,
            source_primary_key TEXT NOT NULL,
            row_payload JSONB NOT NULL,
            row_sha256 CHAR(64) NOT NULL,
            migrated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            PRIMARY KEY (source_table, source_primary_key)
        );
        """
    )


def downgrade() -> None:
    for table_name in (
        "migration_legacy_rows",
        "job_match_results",
        "match_runs",
        "resume_skills",
        "resume_evidence",
        "resumes",
        "user_target_industries",
        "user_target_roles",
        "user_profiles",
        "users",
        "question_embeddings",
        "question_keywords",
        "question_skills",
        "question_roles",
        "question_sources",
        "interview_questions",
        "job_roles",
        "job_skill_requirements",
        "job_source_evidence",
        "job_keywords",
        "job_major_requirements",
        "job_responsibilities",
        "job_analyses",
        "job_versions",
        "job_postings",
        "skill_relations",
        "skill_aliases",
        "skills",
        "role_aliases",
        "roles",
        "ingestion_runs",
        "job_sources",
        "company_industries",
        "industries",
        "companies",
    ):
        op.execute(f"DROP TABLE IF EXISTS {table_name} CASCADE")
