"""Remove unused database skill alias and relation tables.

Revision ID: 20260930_0005
Revises: 20260930_0004
Create Date: 2026-09-30
"""

from typing import Sequence, Union

from alembic import op


revision: str = "20260930_0005"
down_revision: Union[str, None] = "20260930_0004"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute(
        """
        DROP TABLE skill_aliases;
        DROP TABLE skill_relations;
        """
    )


def downgrade() -> None:
    op.execute(
        """
        CREATE TABLE skill_aliases (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            skill_id BIGINT NOT NULL REFERENCES skills(id) ON DELETE CASCADE,
            alias TEXT NOT NULL,
            normalized_alias TEXT NOT NULL UNIQUE
        );
        CREATE INDEX ix_skill_aliases_skill ON skill_aliases(skill_id);

        CREATE TABLE skill_relations (
            source_skill_id BIGINT NOT NULL REFERENCES skills(id) ON DELETE RESTRICT,
            target_skill_id BIGINT NOT NULL REFERENCES skills(id) ON DELETE RESTRICT,
            relation_type TEXT NOT NULL CHECK (
                relation_type IN (
                    'parent_of', 'child_of', 'related_to', 'requires', 'transferable_to'
                )
            ),
            weight NUMERIC(5,4) NOT NULL CHECK (weight >= 0 AND weight <= 1),
            source TEXT,
            PRIMARY KEY (source_skill_id, target_skill_id, relation_type),
            CHECK (source_skill_id <> target_skill_id)
        );
        CREATE INDEX ix_skill_relations_target
            ON skill_relations(target_skill_id, relation_type);
        """
    )
