"""Restore the original single-user profile and resume-history tables.

Revision ID: 20260930_0007
Revises: 20260930_0006
Create Date: 2026-09-30
"""

from typing import Sequence, Union

from alembic import op


revision: str = "20260930_0007"
down_revision: Union[str, None] = "20260930_0006"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute(
        """
        DROP TABLE resume_skills;
        DROP TABLE resume_evidence;
        DROP TABLE resumes;
        DROP TABLE user_target_industries;
        DROP TABLE user_target_roles;
        DROP TABLE user_profiles;
        DROP TABLE users;

        CREATE TABLE user_profile (
            id INTEGER PRIMARY KEY CHECK (id = 1),
            profile_json TEXT NOT NULL,
            updated_at TEXT NOT NULL
        );

        CREATE TABLE resume_uploads (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            filename TEXT,
            resume_json TEXT NOT NULL,
            uploaded_at TEXT NOT NULL
        );
        """
    )


def downgrade() -> None:
    op.execute(
        """
        CREATE TABLE users (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            email TEXT UNIQUE,
            created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
        );

        CREATE TABLE user_profiles (
            user_id BIGINT PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
            profile_payload JSONB NOT NULL,
            notes TEXT NOT NULL DEFAULT '',
            work_authorization TEXT,
            graduation_date DATE,
            updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
        );
        CREATE TABLE user_target_roles (
            user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
            role_id BIGINT NOT NULL REFERENCES roles(id) ON DELETE RESTRICT,
            priority INTEGER NOT NULL CHECK (priority > 0),
            PRIMARY KEY (user_id, role_id),
            UNIQUE (user_id, priority)
        );
        CREATE TABLE user_target_industries (
            user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
            industry_id BIGINT NOT NULL REFERENCES industries(id) ON DELETE RESTRICT,
            PRIMARY KEY (user_id, industry_id)
        );

        CREATE TABLE resumes (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
            legacy_resume_upload_id BIGINT UNIQUE,
            filename TEXT,
            storage_uri TEXT,
            file_hash TEXT,
            parsed_payload JSONB NOT NULL,
            uploaded_at TIMESTAMPTZ NOT NULL,
            created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
        );
        CREATE INDEX ix_resumes_user_uploaded ON resumes(user_id, uploaded_at DESC);
        CREATE TABLE resume_evidence (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            resume_id BIGINT NOT NULL REFERENCES resumes(id) ON DELETE CASCADE,
            evidence_type TEXT NOT NULL CHECK (
                evidence_type IN ('experience', 'project', 'research')
            ),
            sequence_no INTEGER NOT NULL CHECK (sequence_no >= 0),
            title TEXT NOT NULL,
            organization TEXT,
            summary TEXT NOT NULL DEFAULT '',
            raw_payload JSONB NOT NULL DEFAULT '{}'::jsonb,
            embedding VECTOR(384),
            embedding_model TEXT,
            UNIQUE (resume_id, evidence_type, sequence_no)
        );
        CREATE INDEX ix_resume_evidence_resume
            ON resume_evidence(resume_id, evidence_type);
        CREATE INDEX ix_resume_evidence_embedding_hnsw ON resume_evidence
            USING hnsw (embedding vector_cosine_ops) WHERE embedding IS NOT NULL;
        CREATE TABLE resume_skills (
            resume_id BIGINT NOT NULL REFERENCES resumes(id) ON DELETE CASCADE,
            skill_id BIGINT NOT NULL REFERENCES skills(id) ON DELETE RESTRICT,
            sequence_no INTEGER NOT NULL CHECK (sequence_no >= 0),
            source_text TEXT NOT NULL,
            PRIMARY KEY (resume_id, skill_id)
        );
        CREATE INDEX ix_resume_skills_skill ON resume_skills(skill_id, resume_id);

        INSERT INTO users (id)
        SELECT 1
        WHERE EXISTS (SELECT 1 FROM user_profile)
           OR EXISTS (SELECT 1 FROM resume_uploads);
        INSERT INTO user_profiles (user_id, profile_payload, notes, updated_at)
        SELECT id, profile_json::jsonb,
               COALESCE(profile_json::jsonb->'constraints'->>'notes', ''),
               updated_at::timestamptz
        FROM user_profile;
        INSERT INTO resumes (
            id, user_id, legacy_resume_upload_id, filename, parsed_payload, uploaded_at
        )
        SELECT id, 1, id, filename, resume_json::jsonb, uploaded_at::timestamptz
        FROM resume_uploads;
        SELECT setval(
            pg_get_serial_sequence('resumes', 'id'),
            COALESCE((SELECT MAX(id) FROM resumes), 1),
            EXISTS (SELECT 1 FROM resumes)
        );

        DROP TABLE resume_uploads;
        DROP TABLE user_profile;
        """
    )
