"""Remove unused and superseded tables.

Revision ID: 20260930_0003
Revises: 20260930_0002
Create Date: 2026-09-30
"""

from typing import Sequence, Union

from alembic import op


revision: str = "20260930_0003"
down_revision: Union[str, None] = "20260930_0002"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute(
        """
        DROP TABLE job_match_results;
        DROP TABLE match_runs;
        DROP TABLE question_embeddings;
        DROP TABLE job_roles;
        DROP TABLE ingestion_runs;
        """
    )


def downgrade() -> None:
    op.execute(
        """
        CREATE TABLE ingestion_runs (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            source_id BIGINT NOT NULL REFERENCES job_sources(id) ON DELETE RESTRICT,
            status TEXT NOT NULL CHECK (status IN ('running', 'succeeded', 'failed', 'partial')),
            fetched_count INTEGER NOT NULL DEFAULT 0 CHECK (fetched_count >= 0),
            changed_count INTEGER NOT NULL DEFAULT 0 CHECK (changed_count >= 0),
            expired_count INTEGER NOT NULL DEFAULT 0 CHECK (expired_count >= 0),
            error_message TEXT,
            started_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            finished_at TIMESTAMPTZ
        );
        CREATE INDEX ix_ingestion_runs_source_started
            ON ingestion_runs(source_id, started_at DESC);

        CREATE TABLE job_roles (
            job_id BIGINT NOT NULL REFERENCES job_postings(id) ON DELETE CASCADE,
            role_id BIGINT NOT NULL REFERENCES roles(id) ON DELETE RESTRICT,
            confidence NUMERIC(5,4) NOT NULL DEFAULT 1
                CHECK (confidence >= 0 AND confidence <= 1),
            PRIMARY KEY (job_id, role_id)
        );
        CREATE INDEX ix_job_roles_role ON job_roles(role_id, job_id);

        CREATE TABLE question_embeddings (
            question_id BIGINT PRIMARY KEY
                REFERENCES interview_questions(id) ON DELETE CASCADE,
            embedding VECTOR(384),
            raw_embedding JSONB,
            model_name TEXT,
            model_version TEXT,
            created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
        );
        CREATE INDEX ix_question_embeddings_hnsw ON question_embeddings
            USING hnsw (embedding vector_cosine_ops) WHERE embedding IS NOT NULL;

        CREATE TABLE match_runs (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
            resume_id BIGINT NOT NULL REFERENCES resumes(id) ON DELETE RESTRICT,
            algorithm_version TEXT NOT NULL,
            weights JSONB NOT NULL,
            created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
        );
        CREATE INDEX ix_match_runs_user_created
            ON match_runs(user_id, created_at DESC);

        CREATE TABLE job_match_results (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            match_run_id BIGINT NOT NULL REFERENCES match_runs(id) ON DELETE CASCADE,
            job_id BIGINT NOT NULL REFERENCES job_postings(id) ON DELETE RESTRICT,
            required_skill_score NUMERIC(6,3) NOT NULL
                CHECK (required_skill_score BETWEEN 0 AND 100),
            responsibility_score NUMERIC(6,3) NOT NULL
                CHECK (responsibility_score BETWEEN 0 AND 100),
            graph_skill_score NUMERIC(6,3) NOT NULL
                CHECK (graph_skill_score BETWEEN 0 AND 100),
            career_intent_score NUMERIC(6,3) NOT NULL
                CHECK (career_intent_score BETWEEN 0 AND 100),
            preferred_skill_bonus NUMERIC(5,3) NOT NULL
                CHECK (preferred_skill_bonus BETWEEN 0 AND 5),
            final_score NUMERIC(6,3) NOT NULL
                CHECK (final_score BETWEEN 0 AND 100),
            explanation JSONB NOT NULL DEFAULT '{}'::jsonb,
            UNIQUE (match_run_id, job_id)
        );
        CREATE INDEX ix_job_match_results_rank
            ON job_match_results(match_run_id, final_score DESC);
        """
    )
