"""Create the resume-rewrite expert knowledge base and its vector store.

Revision ID: 20261002_0008
Revises: 20260930_0007
Create Date: 2026-10-02
"""

from typing import Sequence, Union

from alembic import op


revision: str = "20261002_0008"
down_revision: Union[str, None] = "20260930_0007"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# 迁移不导入应用代码，取值清单在这里写死；必须与 app/schemas/profile.py 的 TARGET_ROLE_CATEGORIES、
# app/schemas/resume_guideline.py 的 ResumeSection / IssueType 保持一致
ROLE_CATEGORIES = (
    "Software Development",
    "AI & Machine Learning",
    "Data",
    "Quality Assurance & Testing",
    "DevOps & Cloud Infrastructure",
    "Cybersecurity",
    "Product & Project Management",
    "UI/UX Design",
    "Technical Support & Implementation",
    "Hardware & Semiconductors",
)
SECTIONS = ("experience", "project", "research", "skills")
ISSUE_TYPES = (
    "weak_action_verb",
    "missing_quantification",
    "missing_outcome",
    "unclear_tech_stack",
    "weak_jd_alignment",
    "unsurfaced_skill",
    "irrelevant_content",
)


def _array(values: tuple[str, ...]) -> str:
    return "ARRAY[" + ", ".join(f"'{value}'" for value in values) + "]::TEXT[]"


def upgrade() -> None:
    category_rows = ", ".join(f"('{name}')" for name in ROLE_CATEGORIES)
    op.execute(
        f"""
        -- 岗位大类字典：roles.category 与知识库条目共用同一份清单
        CREATE TABLE role_categories (
            name TEXT PRIMARY KEY,
            created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
        );
        INSERT INTO role_categories (name) VALUES {category_rows};
        ALTER TABLE roles
            ADD CONSTRAINT fk_roles_category FOREIGN KEY (category)
            REFERENCES role_categories(name) ON UPDATE CASCADE ON DELETE RESTRICT;

        -- 知识层：出处 → 条目 → 适用大类 / 改写示例，数据以这里为准
        CREATE TABLE guideline_sources (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            name TEXT NOT NULL UNIQUE,
            provider TEXT NOT NULL,
            identifier TEXT NOT NULL,
            url TEXT,
            license TEXT,
            retrieved_at DATE,
            created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
        );

        CREATE TABLE resume_guidelines (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            guideline_key TEXT NOT NULL UNIQUE,
            source_id BIGINT NOT NULL REFERENCES guideline_sources(id) ON DELETE RESTRICT,
            source_url TEXT,
            title TEXT NOT NULL,
            guideline TEXT NOT NULL,
            rationale TEXT NOT NULL,
            sections TEXT[] NOT NULL
                CHECK (cardinality(sections) > 0 AND sections <@ {_array(SECTIONS)}),
            issue_types TEXT[] NOT NULL
                CHECK (cardinality(issue_types) > 0 AND issue_types <@ {_array(ISSUE_TYPES)}),
            status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'retired')),
            content_hash CHAR(64) NOT NULL,
            created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
        );

        -- 没有关联行的条目对所有岗位大类通用
        CREATE TABLE resume_guideline_role_categories (
            guideline_id BIGINT NOT NULL REFERENCES resume_guidelines(id) ON DELETE CASCADE,
            role_category TEXT NOT NULL REFERENCES role_categories(name)
                ON UPDATE CASCADE ON DELETE RESTRICT,
            PRIMARY KEY (guideline_id, role_category)
        );
        CREATE INDEX ix_resume_guideline_role_categories_category
            ON resume_guideline_role_categories(role_category, guideline_id);

        CREATE TABLE resume_guideline_examples (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            guideline_id BIGINT NOT NULL REFERENCES resume_guidelines(id) ON DELETE CASCADE,
            sequence_no INTEGER NOT NULL CHECK (sequence_no >= 0),
            before_text TEXT NOT NULL,
            after_text TEXT NOT NULL,
            UNIQUE (guideline_id, sequence_no)
        );

        -- 向量层：检索单元。说明块（标题 + 建议）每条一个，示例块（改写前原句）每个示例一个；
        -- 向量列写法同 job_responsibilities：模型名 + 内容哈希判断向量是否过期
        CREATE TABLE resume_guideline_chunks (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            guideline_id BIGINT NOT NULL REFERENCES resume_guidelines(id) ON DELETE CASCADE,
            example_id BIGINT REFERENCES resume_guideline_examples(id) ON DELETE CASCADE,
            chunk_type TEXT NOT NULL CHECK (chunk_type IN ('guideline', 'example')),
            chunk_text TEXT NOT NULL,
            content_hash CHAR(64) NOT NULL,
            embedding VECTOR(384),
            embedding_model TEXT,
            embedded_at TIMESTAMPTZ,
            CHECK ((chunk_type = 'example') = (example_id IS NOT NULL)),
            UNIQUE NULLS NOT DISTINCT (guideline_id, example_id)
        );
        CREATE INDEX ix_resume_guideline_chunks_embedding_hnsw ON resume_guideline_chunks
            USING hnsw (embedding vector_cosine_ops) WHERE embedding IS NOT NULL;
        """
    )


def downgrade() -> None:
    op.execute(
        """
        DROP TABLE resume_guideline_chunks;
        DROP TABLE resume_guideline_examples;
        DROP TABLE resume_guideline_role_categories;
        DROP TABLE resume_guidelines;
        DROP TABLE guideline_sources;
        ALTER TABLE roles DROP CONSTRAINT fk_roles_category;
        DROP TABLE role_categories;
        """
    )
