"""Remove interview-question skill and keyword tags.

Revision ID: 20260930_0006
Revises: 20260930_0005
Create Date: 2026-09-30
"""

from typing import Sequence, Union

from alembic import op


revision: str = "20260930_0006"
down_revision: Union[str, None] = "20260930_0005"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute(
        """
        DROP TABLE question_skills;
        DROP TABLE question_keywords;

        DELETE FROM skills skill
        WHERE NOT EXISTS (
            SELECT 1 FROM job_skill_requirements requirement
            WHERE requirement.skill_id = skill.id
        )
          AND NOT EXISTS (
            SELECT 1 FROM resume_skills resume_skill
            WHERE resume_skill.skill_id = skill.id
        );
        """
    )


def downgrade() -> None:
    op.execute(
        """
        CREATE TABLE question_skills (
            question_id BIGINT NOT NULL
                REFERENCES interview_questions(id) ON DELETE CASCADE,
            skill_id BIGINT NOT NULL REFERENCES skills(id) ON DELETE RESTRICT,
            sequence_no INTEGER NOT NULL CHECK (sequence_no >= 0),
            source_text TEXT NOT NULL,
            relevance NUMERIC(5,4) NOT NULL DEFAULT 1
                CHECK (relevance >= 0 AND relevance <= 1),
            PRIMARY KEY (question_id, skill_id)
        );
        CREATE INDEX ix_question_skills_skill
            ON question_skills(skill_id, question_id);

        CREATE TABLE question_keywords (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            question_id BIGINT NOT NULL
                REFERENCES interview_questions(id) ON DELETE CASCADE,
            sequence_no INTEGER NOT NULL CHECK (sequence_no >= 0),
            keyword_text TEXT NOT NULL,
            UNIQUE (question_id, sequence_no)
        );
        """
    )
